# Data Preparation and Analysis 

### Import Libraries

In [59]:
library(ggplot2)
library(reshape)
suppressMessages(library(dplyr))
suppressMessages(library(tidyverse))

### Importing data

In [60]:
results = read.csv("../premier-league/data/results.csv")
stats = read.csv("../premier-league/data/stats.csv")
df0607 = read.csv("../premier-league/data/season-0607.csv")
df0708 = read.csv("../premier-league/data/season-0708.csv")
df0809 = read.csv("../premier-league/data/season-0809.csv")
df0910 = read.csv("../premier-league/data/season-0910.csv")
df1011 = read.csv("../premier-league/data/season-1011.csv")
df1112 = read.csv("../premier-league/data/season-1112.csv")
df1213 = read.csv("../premier-league/data/season-1213.csv")
df1314 = read.csv("../premier-league/data/season-1314.csv")
df1415 = read.csv("../premier-league/data/season-1415.csv")
df1516 = read.csv("../premier-league/data/season-1516.csv")
df1617 = read.csv("../premier-league/data/season-1617.csv")
df1718 = read.csv("../premier-league/data/season-1718.csv")

In [61]:
#Checking top few rows of datasets
head(results)
head(stats)
head(df0607)

home_team        away_team        home_goals away_goals result season   
1 Sheffield United Liverpool        1          1          D      2006-2007
2 Arsenal          Aston Villa      1          1          D      2006-2007
3 Everton          Watford          2          1          H      2006-2007
4 Newcastle United Wigan Athletic   2          1          H      2006-2007
5 Portsmouth       Blackburn Rovers 3          0          H      2006-2007
6 Reading          Middlesbrough    3          2          H      2006-2007

team              wins losses goals total_yel_card total_red_card
1 Manchester United 28    5     83    60             1             
2 Chelsea           24    3     64    62             4             
3 Liverpool         20   10     57    44             0             
4 Arsenal           19    8     63    59             3             
5 Tottenham Hotspur 17   12     57    48             3             
6 Bolton Wanderers  16   14     47    84             4             
  total_scoring_att ontarget_scoring_att hit_woodwork att_hd_goal ⋯ total_cross
1 698               256                  21           12          ⋯  918       
2 636               216                  14           16          ⋯  897       
3 668               214                  15            8          ⋯ 1107       
4 638               226                  19           10          ⋯  873       
5 520               184                   6            5          ⋯  796       
6 404               120                   7           10          ⋯  942       
  corner_taken touches big_chance_missed clearance_off_line dispossessed
1 258          25686   NA                1                  NA          
2 231          24010   NA                2                  NA          
3 282          24150   NA                1                  NA          
4 278          25592   NA                1                  NA          
5 181          22200   NA                2                  NA          
6 217          18932   NA                6                  NA          
  penalty_save total_high_claim punches season   
1 2            37               25      2006-2007
2 1            74               22      2006-2007
3 0            51               27      2006-2007
4 0            88               27      2006-2007
5 0            51               24      2006-2007
6 2            44               21      2006-2007

Div Date       HomeTeam   AwayTeam      FTHG FTAG FTR HTHG HTAG HTR ⋯ HST AST
1 E0  19-08-2006 Arsenal    Aston Villa   1    1    D   0    0    D   ⋯ 11  3  
2 E0  19-08-2006 Bolton     Tottenham     2    0    H   2    0    H   ⋯  6  6  
3 E0  19-08-2006 Everton    Watford       2    1    H   1    0    H   ⋯  2  8  
4 E0  19-08-2006 Newcastle  Wigan         2    1    H   1    0    H   ⋯  8  9  
5 E0  19-08-2006 Portsmouth Blackburn     3    0    H   1    0    H   ⋯ 16  7  
6 E0  19-08-2006 Reading    Middlesbrough 3    2    H   2    2    D   ⋯  9  5  
  HF AF HC AC HY AY HR AR
1 10 19 18  1 1  2  0  0 
2 19 22  6  3 0  1  0  0 
3 12 13  0  6 2  2  0  0 
4 17 20  4 11 1  2  0  0 
5 20 17  6  2 2  1  0  2 
6  8 15  8  2 1  3  0  0

In [62]:
#Checking top few rows of season 09-10
head(df0910)

Date       HomeTeam    AwayTeam   FTHG FTAG FTR HTHG HTAG HTR Referee       ⋯
1 2009-08-15 Aston Villa Wigan      0    2    A   0    1    A   M Clattenburg ⋯
2 2009-08-15 Blackburn   Man City   0    2    A   0    1    A   M Dean        ⋯
3 2009-08-15 Bolton      Sunderland 0    1    A   0    1    A   A Marriner    ⋯
4 2009-08-15 Chelsea     Hull       2    1    H   1    1    D   A Wiley       ⋯
5 2009-08-15 Everton     Arsenal    1    6    A   0    3    A   M Halsey      ⋯
6 2009-08-15 Portsmouth  Fulham     0    1    A   0    1    A   M Atkinson    ⋯
  HST AST HF AF HC AC HY AY HR AR
1  5   7  15 14  4 6  2  2  0  0 
2  9   5  12  9  5 4  2  1  0  0 
3  3  13  16 10  4 7  2  1  0  0 
4 12   3  13 15 12 4  1  2  0  0 
5  5   9  11 13  4 9  0  0  0  0 
6  4   3  11 18  6 4  3  2  0  0

In [63]:
#Checking top few rows of season 08-09
head(df0809)

Div Date     HomeTeam      AwayTeam   FTHG FTAG FTR HTHG HTAG HTR ⋯ BbMx.2.5
1 E0  11/08/07 Aston Villa   Liverpool  1    2    A   0    1    A   ⋯ 2.30    
2 E0  11/08/07 Bolton        Newcastle  1    3    A   0    3    A   ⋯ 2.33    
3 E0  11/08/07 Derby         Portsmouth 2    2    D   1    1    D   ⋯ 2.35    
4 E0  11/08/07 Everton       Wigan      2    1    H   1    0    H   ⋯ 2.20    
5 E0  11/08/07 Middlesbrough Blackburn  1    2    A   1    0    H   ⋯ 2.30    
6 E0  11/08/07 Sunderland    Tottenham  1    0    H   0    0    D   ⋯ 2.15    
  BbAv.2.5 BbMx.2.5.1 BbAv.2.5.1 BbAH BbAHh BbMxAHH BbAvAHH BbMxAHA BbAvAHA
1 2.14     1.70       1.63       26    0.50 1.95    1.85    2.07    1.95   
2 2.10     1.75       1.65       26    0.00 1.83    1.75    2.18    2.04   
3 2.13     1.90       1.63       25    0.00 2.26    2.09    1.76    1.71   
4 2.00     1.83       1.73       26   -0.75 1.97    1.94    2.02    1.94   
5 2.08     1.75       1.67       26    0.00 1.90    1.77    2.10    1.97   
6 2.04     1.83       1.70       26    0.25 2.06    2.09    1.82    1.79

In [64]:
#removing unwanted columns in season 2006-2008 to maake total columns consistent from season 2006-2018
df0607  <- df0607[2:23]
df0708  <- df0708[2:23]
df0809  <- df0809[2:23]

In [65]:
#checking number of rows adn columns in a seasons dataframe
dim(df0708)
dim(df1718)
dim(df1415)

[1] 380  22

[1] 380  22

[1] 380  22

In [66]:
#Merging season 2006-2018 dataframs
df  <- do.call("rbind", list(df0607,df0708,df0809,df0910,df1011,df1112,df1213,df1314,df1415,df1516,df1617,df1718))

In [67]:
#checking number of rows and columns in a dataframe
dim(df)

[1] 4560   22

The merged data frame has total 380*12 = 4560 rows which is corrext expected output.

In [68]:
#Checking top few rows of dataframe
head(df)

Date       HomeTeam   AwayTeam      FTHG FTAG FTR HTHG HTAG HTR Referee    ⋯
1 19-08-2006 Arsenal    Aston Villa   1    1    D   0    0    D   G Poll     ⋯
2 19-08-2006 Bolton     Tottenham     2    0    H   2    0    H   P Dowd     ⋯
3 19-08-2006 Everton    Watford       2    1    H   1    0    H   P Walton   ⋯
4 19-08-2006 Newcastle  Wigan         2    1    H   1    0    H   M Atkinson ⋯
5 19-08-2006 Portsmouth Blackburn     3    0    H   1    0    H   A Wiley    ⋯
6 19-08-2006 Reading    Middlesbrough 3    2    H   2    2    D   M Halsey   ⋯
  HST AST HF AF HC AC HY AY HR AR
1 11  3   10 19 18  1 1  2  0  0 
2  6  6   19 22  6  3 0  1  0  0 
3  2  8   12 13  0  6 2  2  0  0 
4  8  9   17 20  4 11 1  2  0  0 
5 16  7   20 17  6  2 2  1  0  2 
6  9  5    8 15  8  2 1  3  0  0

In [69]:
#saving the dataframe df data into a csv file
write.csv(df, file = "../premier-league/data/season06-18.csv",row.names=FALSE)

In [70]:
#reading the all seasons csv.
results = read.csv("../premier-league/data/results.csv")
stats = read.csv("../premier-league/data/stats.csv")
df  <- read.csv("../premier-league/data/season06-18.csv")

In [71]:
#checking the structure of dataframe
str(df)

'data.frame':	4560 obs. of  22 variables:
 $ Date    : Factor w/ 1109 levels "01-01-2007","01-04-2007",..: 112 112 112 112 112 112 112 112 119 119 ...
 $ HomeTeam: Factor w/ 39 levels "Arsenal","Aston Villa",..: 1 6 15 24 26 28 29 37 12 22 ...
 $ AwayTeam: Factor w/ 39 levels "Arsenal","Aston Villa",..: 2 34 35 38 4 23 20 11 21 16 ...
 $ FTHG    : int  1 2 2 2 3 3 1 3 3 5 ...
 $ FTAG    : int  1 0 1 1 0 2 1 1 0 1 ...
 $ FTR     : Factor w/ 3 levels "A","D","H": 2 3 3 3 3 3 2 3 3 3 ...
 $ HTHG    : int  0 2 1 1 1 2 0 0 2 4 ...
 $ HTAG    : int  0 0 0 0 0 2 0 1 0 1 ...
 $ HTR     : Factor w/ 3 levels "A","D","H": 2 3 3 3 3 2 2 1 3 3 ...
 $ Referee : Factor w/ 40 levels "A Marriner","A Taylor",..: 11 29 31 20 3 23 34 13 36 1 ...
 $ HS      : int  19 8 6 9 21 14 5 16 10 15 ...
 $ AS      : int  5 9 12 14 9 7 12 4 5 12 ...
 $ HST     : int  11 6 2 8 16 9 3 5 4 7 ...
 $ AST     : int  3 6 8 9 7 5 7 2 2 8 ...
 $ HF      : int  10 19 12 17 20 8 10 14 7 14 ...
 $ AF      : int  19 22 13 20 17 1

In [72]:
#checking the structure of stats dataframe
str(stats)

'data.frame':	240 obs. of  42 variables:
 $ team                : Factor w/ 39 levels "AFC Bournemouth",..: 22 12 20 2 34 7 28 5 15 26 ...
 $ wins                : num  28 24 20 19 17 16 16 15 15 14 ...
 $ losses              : num  5 3 10 8 12 14 15 16 10 12 ...
 $ goals               : num  83 64 57 63 57 47 52 52 52 45 ...
 $ total_yel_card      : num  60 62 44 59 48 84 38 77 65 48 ...
 $ total_red_card      : num  1 4 0 3 3 4 3 6 2 1 ...
 $ total_scoring_att   : num  698 636 668 638 520 404 419 478 465 525 ...
 $ ontarget_scoring_att: num  256 216 214 226 184 120 132 155 153 186 ...
 $ hit_woodwork        : num  21 14 15 19 6 7 8 5 9 9 ...
 $ att_hd_goal         : num  12 16 8 10 5 10 15 12 9 13 ...
 $ att_pen_goal        : num  5 3 6 10 6 6 3 5 8 2 ...
 $ att_freekick_goal   : num  1 6 1 3 2 0 0 3 2 0 ...
 $ att_ibox_goal       : num  72 41 46 53 44 38 42 43 44 32 ...
 $ att_obox_goal       : num  11 23 11 10 13 9 10 9 8 13 ...
 $ goal_fastbreak      : num  9 6 3 7 9 3 3 2 3 2 ...

In [73]:
#displaying all the teams that played from 2006-2018 seasons
levels(stats$team)

[1] "AFC Bournemouth"          "Arsenal"                 
 [3] "Aston Villa"              "Birmingham City"         
 [5] "Blackburn Rovers"         "Blackpool"               
 [7] "Bolton Wanderers"         "Brighton and Hove Albion"
 [9] "Burnley"                  "Cardiff City"            
[11] "Charlton Athletic"        "Chelsea"                 
[13] "Crystal Palace"           "Derby County"            
[15] "Everton"                  "Fulham"                  
[17] "Huddersfield Town"        "Hull City"               
[19] "Leicester City"           "Liverpool"               
[21] "Manchester City"          "Manchester United"       
[23] "Middlesbrough"            "Newcastle United"        
[25] "Norwich City"             "Portsmouth"              
[27] "Queens Park Rangers"      "Reading"                 
[29] "Sheffield United"         "Southampton"             
[31] "Stoke City"               "Sunderland"              
[33] "Swansea City"             "Tottenham Hotspur"       
[35] "Watford"                  "West Bromwich Albion"    
[37] "West Ham United"          "Wigan Athletic"          
[39] "Wolverhampton Wanderers"

Total 39 teams have participated in 12 seasons and each season consists of 20 teams

In [74]:
#checking for missing values in stats column
stats[!complete.cases(stats),]

team                    wins losses goals total_yel_card total_red_card
1  Manchester United       28    5     83    60             1             
2  Chelsea                 24    3     64    62             4             
3  Liverpool               20   10     57    44             0             
4  Arsenal                 19    8     63    59             3             
5  Tottenham Hotspur       17   12     57    48             3             
6  Bolton Wanderers        16   14     47    84             4             
7  Reading                 16   15     52    38             3             
8  Blackburn Rovers        15   16     52    77             6             
9  Everton                 15   10     52    65             2             
10 Portsmouth              14   12     45    48             1             
11 Middlesbrough           12   16     44    64             2             
12 West Ham United         12   21     35    85             2             
13 Aston Villa             11   10     43    48             1             
14 Manchester City         11   18     29    59             4             
15 Newcastle United        11   17     38    65             1             
16 Sheffield United        10   20     32    68             2             
17 Wigan Athletic          10   20     37    73             3             
18 Charlton Athletic        8   20     34    56             4             
19 Fulham                   8   15     38    56             3             
20 Watford                  5   20     29    45             2             
21 Manchester United       27    5     80    51             2             
22 Chelsea                 25    3     65    63             5             
23 Arsenal                 24    3     74    55             3             
24 Liverpool               21    4     67    45             1             
25 Everton                 19   11     55    40             3             
26 Aston Villa             16   10     71    54             4             
27 Portsmouth              16   13     48    55             3             
28 Blackburn Rovers        15   10     50    72             6             
29 Manchester City         15   13     45    50             4             
30 West Ham United         13   15     42    63             1             
⋮  ⋮                       ⋮    ⋮      ⋮     ⋮              ⋮             
51 Stoke City              12   17      38   73             5             
52 Wigan Athletic          12   17      34   59             4             
53 Bolton Wanderers        11   19      41   62             1             
54 Blackburn Rovers        10   17      40   74             4             
55 Portsmouth              10   17      38   58             5             
56 Sunderland               9   20      34   69             1             
57 Hull City                8   19      39   71             3             
58 West Bromwich Albion     8   22      36   67             1             
59 Middlesbrough            7   20      28   55             3             
60 Newcastle United         7   18      40   57             8             
61 Chelsea                 27    6     103   54             5             
62 Manchester United       27    7      86   49             4             
63 Arsenal                 23    9      83   56             1             
64 Tottenham Hotspur       21   10      67   58             1             
65 Liverpool               18   11      61   55             5             
66 Manchester City         18    7      73   49             2             
67 Aston Villa             17    8      52   59             2             
68 Everton                 16    9      60   57             2             
69 Birmingham City         13   14      38   74             1             
70 Blackburn Rovers        13   14      41   57             2             
71 Fulham                  12   16      39   46             1             
72 Stoke City              1

In [75]:
head(results)
head(stats)
head(df)

home_team        away_team        home_goals away_goals result season   
1 Sheffield United Liverpool        1          1          D      2006-2007
2 Arsenal          Aston Villa      1          1          D      2006-2007
3 Everton          Watford          2          1          H      2006-2007
4 Newcastle United Wigan Athletic   2          1          H      2006-2007
5 Portsmouth       Blackburn Rovers 3          0          H      2006-2007
6 Reading          Middlesbrough    3          2          H      2006-2007

team              wins losses goals total_yel_card total_red_card
1 Manchester United 28    5     83    60             1             
2 Chelsea           24    3     64    62             4             
3 Liverpool         20   10     57    44             0             
4 Arsenal           19    8     63    59             3             
5 Tottenham Hotspur 17   12     57    48             3             
6 Bolton Wanderers  16   14     47    84             4             
  total_scoring_att ontarget_scoring_att hit_woodwork att_hd_goal ⋯ total_cross
1 698               256                  21           12          ⋯  918       
2 636               216                  14           16          ⋯  897       
3 668               214                  15            8          ⋯ 1107       
4 638               226                  19           10          ⋯  873       
5 520               184                   6            5          ⋯  796       
6 404               120                   7           10          ⋯  942       
  corner_taken touches big_chance_missed clearance_off_line dispossessed
1 258          25686   NA                1                  NA          
2 231          24010   NA                2                  NA          
3 282          24150   NA                1                  NA          
4 278          25592   NA                1                  NA          
5 181          22200   NA                2                  NA          
6 217          18932   NA                6                  NA          
  penalty_save total_high_claim punches season   
1 2            37               25      2006-2007
2 1            74               22      2006-2007
3 0            51               27      2006-2007
4 0            88               27      2006-2007
5 0            51               24      2006-2007
6 2            44               21      2006-2007

Date       HomeTeam   AwayTeam      FTHG FTAG FTR HTHG HTAG HTR Referee    ⋯
1 19-08-2006 Arsenal    Aston Villa   1    1    D   0    0    D   G Poll     ⋯
2 19-08-2006 Bolton     Tottenham     2    0    H   2    0    H   P Dowd     ⋯
3 19-08-2006 Everton    Watford       2    1    H   1    0    H   P Walton   ⋯
4 19-08-2006 Newcastle  Wigan         2    1    H   1    0    H   M Atkinson ⋯
5 19-08-2006 Portsmouth Blackburn     3    0    H   1    0    H   A Wiley    ⋯
6 19-08-2006 Reading    Middlesbrough 3    2    H   2    2    D   M Halsey   ⋯
  HST AST HF AF HC AC HY AY HR AR
1 11  3   10 19 18  1 1  2  0  0 
2  6  6   19 22  6  3 0  1  0  0 
3  2  8   12 13  0  6 2  2  0  0 
4  8  9   17 20  4 11 1  2  0  0 
5 16  7   20 17  6  2 2  1  0  2 
6  9  5    8 15  8  2 1  3  0  0

### Adding manager data to Manchester united

In [76]:
#seperating Manchester united column from stats table
ManUnited  <- stats[stats$team == 'Manchester United',]

In [77]:
head(ManUnited)

team              wins losses goals total_yel_card total_red_card
1   Manchester United 28   5      83    60             1             
21  Manchester United 27   5      80    51             2             
41  Manchester United 28   4      68    61             5             
62  Manchester United 27   7      86    49             4             
81  Manchester United 23   4      78    56             3             
102 Manchester United 28   5      89    51             1             
    total_scoring_att ontarget_scoring_att hit_woodwork att_hd_goal ⋯
1   698               256                  21           12          ⋯
21  696               260                  16           12          ⋯
41  715               230                   9            7          ⋯
62  695               221                  12           14          ⋯
81  618               212                  15           18          ⋯
102 646               243                  17           16          ⋯
    total_cross corner_taken touches big_chance_missed clearance_off_line
1    918        258          25686   NA                 1                
21   936        261          26620   NA                10                
41  1039        257          30077   NA                 3                
62  1156        297          28968   NA                 2                
81  1005        243          26671   50                 2                
102 1018        279          28113   64                 3                
    dispossessed penalty_save total_high_claim punches season   
1    NA          2            37               25      2006-2007
21  627          0            47               23      2007-2008
41  579          0            56               22      2008-2009
62  622          0            65               18      2009-2010
81  471          0            45               16      2010-2011
102 521          1            37               26      2011-2012

In [78]:
#resetting rownames
rownames(ManUnited) <- NULL

In [79]:
#Adding Manager data
ManUnited$manager  <- rep("Alex Ferguson",nrow(ManUnited))
ManUnited[ManUnited$season == "2013-2014","manager"]  <- "David Moyes"
ManUnited[ManUnited$season == "2014-2015","manager"]  <- "Louis van Gaal"
ManUnited[ManUnited$season == "2015-2016","manager"]  <- "Louis van Gaal"
ManUnited[ManUnited$season == "2016-2017","manager"]  <- "Jose Mourinho"
ManUnited[ManUnited$season == "2017-2018","manager"]  <- "Jose Mourinho"

In [80]:
#Manchester united dataframe
ManUnited

team              wins losses goals total_yel_card total_red_card
1  Manchester United 28    5     83    60             1             
2  Manchester United 27    5     80    51             2             
3  Manchester United 28    4     68    61             5             
4  Manchester United 27    7     86    49             4             
5  Manchester United 23    4     78    56             3             
6  Manchester United 28    5     89    51             1             
7  Manchester United 28    5     86    57             1             
8  Manchester United 19   12     64    66             3             
9  Manchester United 20    8     62    64             5             
10 Manchester United 19   10     49    65             1             
11 Manchester United 18    5     54    78             2             
12 Manchester United 25    7     68    64             1             
   total_scoring_att ontarget_scoring_att hit_woodwork att_hd_goal ⋯
1  698               256                  21           12          ⋯
2  696               260                  16           12          ⋯
3  715               230                   9            7          ⋯
4  695               221                  12           14          ⋯
5  618               212                  15           18          ⋯
6  646               243                  17           16          ⋯
7  561               213                  24           14          ⋯
8  526               183                  16           10          ⋯
9  512               180                  11           12          ⋯
10 430               144                   9            5          ⋯
11 591               210                  19            9          ⋯
12 512               178                  16           12          ⋯
   corner_taken touches big_chance_missed clearance_off_line dispossessed
1  258          25686   NA                 1                  NA         
2  261          26620   NA                10                 627         
3  257          30077   NA                 3                 579         
4  297          28968   NA                 2                 622         
5  243          26671   50                 2                 471         
6  279          28113   64                 3                 521         
7  218          27264   65                 5                 506         
8  216          27367   38                 1                 491         
9  214          29044   43                 5                 393         
10 228          27542   28                 4                 522         
11 217          28119   50                 1                 389         
12 220          27525   42                 4                 399         
   penalty_save total_high_claim punches season    manager       
1  2            37               25      2006-2007 Alex Ferguson 
2  0            47               23      2007-2008 Alex Ferguson 
3  0            56               22      2008-2009 Alex Ferguson 
4  0            65               18      2009-2010 Alex Ferguson 
5  0            45               16      2010-2011 Alex Ferguson 
6  1            37               26      2011-2012 Alex Ferguson 
7  0            38               28      2012-2013 Alex Ferguson 
8  0            32               14      2013-2014 David Moyes   
9  1            33                7      2014-2015 Louis van Gaal
10 0            29               13      2015-2016 Louis van Gaal
11 1            32                4      2016-2017 Jose Mourinho 
12 0            20                6      2017-2018 Jose Mourinho

In [81]:
#saving the Manchester United dataframe as a csv file
write.csv(ManUnited, file = "../premier-league/data/ManU.csv",row.names=FALSE)

In [82]:
ManUnited  <- read_csv("../premier-league/data/ManU.csv")
ManUnited

Parsed with column specification:
cols(
  .default = col_integer(),
  team = col_character(),
  season = col_character(),
  manager = col_character()
)
See spec(...) for full column specifications.


team              wins losses goals total_yel_card total_red_card
1  Manchester United 28    5     83    60             1             
2  Manchester United 27    5     80    51             2             
3  Manchester United 28    4     68    61             5             
4  Manchester United 27    7     86    49             4             
5  Manchester United 23    4     78    56             3             
6  Manchester United 28    5     89    51             1             
7  Manchester United 28    5     86    57             1             
8  Manchester United 19   12     64    66             3             
9  Manchester United 20    8     62    64             5             
10 Manchester United 19   10     49    65             1             
11 Manchester United 18    5     54    78             2             
12 Manchester United 25    7     68    64             1             
   total_scoring_att ontarget_scoring_att hit_woodwork att_hd_goal ⋯
1  698               256                  21           12          ⋯
2  696               260                  16           12          ⋯
3  715               230                   9            7          ⋯
4  695               221                  12           14          ⋯
5  618               212                  15           18          ⋯
6  646               243                  17           16          ⋯
7  561               213                  24           14          ⋯
8  526               183                  16           10          ⋯
9  512               180                  11           12          ⋯
10 430               144                   9            5          ⋯
11 591               210                  19            9          ⋯
12 512               178                  16           12          ⋯
   corner_taken touches big_chance_missed clearance_off_line dispossessed
1  258          25686   NA                 1                  NA         
2  261          26620   NA                10                 627         
3  257          30077   NA                 3                 579         
4  297          28968   NA                 2                 622         
5  243          26671   50                 2                 471         
6  279          28113   64                 3                 521         
7  218          27264   65                 5                 506         
8  216          27367   38                 1                 491         
9  214          29044   43                 5                 393         
10 228          27542   28                 4                 522         
11 217          28119   50                 1                 389         
12 220          27525   42                 4                 399         
   penalty_save total_high_claim punches season    manager       
1  2            37               25      2006-2007 Alex Ferguson 
2  0            47               23      2007-2008 Alex Ferguson 
3  0            56               22      2008-2009 Alex Ferguson 
4  0            65               18      2009-2010 Alex Ferguson 
5  0            45               16      2010-2011 Alex Ferguson 
6  1            37               26      2011-2012 Alex Ferguson 
7  0            38               28      2012-2013 Alex Ferguson 
8  0            32               14      2013-2014 David Moyes   
9  1            33                7      2014-2015 Louis van Gaal
10 0            29               13      2015-2016 Louis van Gaal
11 1            32                4      2016-2017 Jose Mourinho 
12 0            20                6      2017-2018 Jose Mourinho

In [83]:
?write.csv

team        wins losses goals total_yel_card total_red_card
135 Southampton  9   15     49    43             2             
149 Southampton 15   12     54    60             0             
167 Southampton 18   14     54    57             3             
186 Southampton 18   11     59    57             6             
211 Southampton 12   16     41    59             2             
238 Southampton  7   16     37    63             2             
    total_scoring_att ontarget_scoring_att hit_woodwork att_hd_goal ⋯
135 516               167                  16            9          ⋯
149 534               179                  16           10          ⋯
167 509               169                  17            3          ⋯
186 519               166                  13           15          ⋯
211 550               179                  12            4          ⋯
238 450               145                  15            7          ⋯
    total_cross corner_taken touches big_chance_missed clearance_off_line
135 917         209          25365   41                3                 
149 877         210          28030   37                1                 
167 952         208          25815   44                4                 
186 956         220          23716   43                6                 
211 947         198          25881   34                4                 
238 800         227          24639   37                4                 
    dispossessed penalty_save total_high_claim punches season   
135 477          3            56               16      2012-2013
149 522          0            50               18      2013-2014
167 422          0            50               15      2014-2015
186 425          0            36               12      2015-2016
211 455          1            26               12      2016-2017
238 379          1            29               13      2017-2018

In [95]:
#Adding total games played column to the stats dataframe
stats$total_games  <- rep(38,nrow(stats))

In [96]:
head(stats,20)

team              wins losses goals total_yel_card total_red_card
1 Manchester United 28    5     83    60             1             
2 Chelsea           24    3     64    62             4             
3 Liverpool         20   10     57    44             0             
4 Arsenal           19    8     63    59             3             
5 Tottenham Hotspur 17   12     57    48             3             
6 Bolton Wanderers  16   14     47    84             4             
  total_scoring_att ontarget_scoring_att hit_woodwork att_hd_goal ⋯
1 698               256                  21           12          ⋯
2 636               216                  14           16          ⋯
3 668               214                  15            8          ⋯
4 638               226                  19           10          ⋯
5 520               184                   6            5          ⋯
6 404               120                   7           10          ⋯
  corner_taken touches big_chance_missed clearance_off_line dispossessed
1 258          25686   NA                1                  NA          
2 231          24010   NA                2                  NA          
3 282          24150   NA                1                  NA          
4 278          25592   NA                1                  NA          
5 181          22200   NA                2                  NA          
6 217          18932   NA                6                  NA          
  penalty_save total_high_claim punches season    total_games
1 2            37               25      2006-2007 38         
2 1            74               22      2006-2007 38         
3 0            51               27      2006-2007 38         
4 0            88               27      2006-2007 38         
5 0            51               24      2006-2007 38         
6 2            44               21      2006-2007 38

In [97]:
#saving the stats dataframe
write.csv(stats,file = "../premier-league/data/stats.csv",row.names=FALSE)

In [99]:
stats  <- read_csv("../premier-league/data/stats.csv")

Parsed with column specification:
cols(
  .default = col_integer(),
  team = col_character(),
  season = col_character()
)
See spec(...) for full column specifications.


### Extracting Leicester City stats from stats dataframe

In [113]:
unique(stats$team)

[1] "Manchester United"        "Chelsea"                 
 [3] "Liverpool"                "Arsenal"                 
 [5] "Tottenham Hotspur"        "Bolton Wanderers"        
 [7] "Reading"                  "Blackburn Rovers"        
 [9] "Everton"                  "Portsmouth"              
[11] "Middlesbrough"            "West Ham United"         
[13] "Aston Villa"              "Manchester City"         
[15] "Newcastle United"         "Sheffield United"        
[17] "Wigan Athletic"           "Charlton Athletic"       
[19] "Fulham"                   "Watford"                 
[21] "Sunderland"               "Birmingham City"         
[23] "Derby County"             "Stoke City"              
[25] "Hull City"                "West Bromwich Albion"    
[27] "Wolverhampton Wanderers"  "Burnley"                 
[29] "Blackpool"                "Norwich City"            
[31] "Swansea City"             "Queens Park Rangers"     
[33] "Southampton"              "Crystal Palace"          
[35] "Cardiff City"             "Leicester City"          
[37] "AFC Bournemouth"          "Brighton and Hove Albion"
[39] "Huddersfield Town"

In [114]:
Leicester  <- stats[stats$team=='Leicester City',]

In [115]:
Leicester

team           wins losses goals total_yel_card total_red_card
1 Leicester City 11   19     46    49             4             
2 Leicester City 23    3     68    48             3             
3 Leicester City 12   18     48    72             1             
4 Leicester City 12   15     56    52             5             
  total_scoring_att ontarget_scoring_att hit_woodwork att_hd_goal ⋯
1 456               137                  12            7          ⋯
2 522               179                  11           11          ⋯
3 433               145                   8           10          ⋯
4 423               149                   8            9          ⋯
  corner_taken touches big_chance_missed clearance_off_line dispossessed
1 211          21547   44                2                  355         
2 197          21710   61                7                  366         
3 197          21051   29                2                  310         
4 203          22770   35                4                  358         
  penalty_save total_high_claim punches season    total_games
1 0            38               26      2014-2015 38         
2 0            49               22      2015-2016 38         
3 0            45               16      2016-2017 38         
4 2            29               23      2017-2018 38

In [116]:
write.csv(Leicester,file="../premier-league/data/leicester.csv",row.names=FALSE)

### Incorrect values in saves column in stats dataframe

In [117]:
head(stats)

team              wins losses goals total_yel_card total_red_card
1 Manchester United 28    5     83    60             1             
2 Chelsea           24    3     64    62             4             
3 Liverpool         20   10     57    44             0             
4 Arsenal           19    8     63    59             3             
5 Tottenham Hotspur 17   12     57    48             3             
6 Bolton Wanderers  16   14     47    84             4             
  total_scoring_att ontarget_scoring_att hit_woodwork att_hd_goal ⋯
1 698               256                  21           12          ⋯
2 636               216                  14           16          ⋯
3 668               214                  15            8          ⋯
4 638               226                  19           10          ⋯
5 520               184                   6            5          ⋯
6 404               120                   7           10          ⋯
  corner_taken touches big_chance_missed clearance_off_line dispossessed
1 258          25686   NA                1                  NA          
2 231          24010   NA                2                  NA          
3 282          24150   NA                1                  NA          
4 278          25592   NA                1                  NA          
5 181          22200   NA                2                  NA          
6 217          18932   NA                6                  NA          
  penalty_save total_high_claim punches season    total_games
1 2            37               25      2006-2007 38         
2 1            74               22      2006-2007 38         
3 0            51               27      2006-2007 38         
4 0            88               27      2006-2007 38         
5 0            51               24      2006-2007 38         
6 2            44               21      2006-2007 38

In [118]:
unique(stats$season)

[1] "2006-2007" "2007-2008" "2008-2009" "2009-2010" "2010-2011" "2011-2012"
 [7] "2012-2013" "2013-2014" "2014-2015" "2015-2016" "2016-2017" "2017-2018"

In [122]:
stats[stats$season=='2007-2008',c('team','saves')]

team              saves
1  Manchester United 2    
2  Chelsea           4    
3  Arsenal           0    
4  Liverpool         0    
5  Everton           0    
6  Aston Villa       3    
7  Portsmouth        4    
8  Blackburn Rovers  0    
9  Manchester City   4    
10 West Ham United   1    
11 Newcastle United  0    
12 Sunderland        0    
13 Tottenham Hotspur 0    
14 Middlesbrough     0    
15 Reading           7    
16 Wigan Athletic    5    
17 Bolton Wanderers  0    
18 Birmingham City   0    
19 Fulham            0    
20 Derby County      8

### Saves from season 2006/2007 - 2012/2013 were not recorded properly

In [127]:
#missing dispossed values in season 2006/2007
stats[stats$season == '2006-2007',c('team','dispossessed')]

team              dispossessed
1  Manchester United NA          
2  Chelsea           NA          
3  Liverpool         NA          
4  Arsenal           NA          
5  Tottenham Hotspur NA          
6  Bolton Wanderers  NA          
7  Reading           NA          
8  Blackburn Rovers  NA          
9  Everton           NA          
10 Portsmouth        NA          
11 Middlesbrough     NA          
12 West Ham United   NA          
13 Aston Villa       NA          
14 Manchester City   NA          
15 Newcastle United  NA          
16 Sheffield United  NA          
17 Wigan Athletic    NA          
18 Charlton Athletic NA          
19 Fulham            NA          
20 Watford           NA

In [131]:
sum(!complete.cases(stats))

[1] 80

In [124]:
stats[!complete.cases(stats),]

team                    wins losses goals total_yel_card total_red_card
1  Manchester United       28    5     83    60             1             
2  Chelsea                 24    3     64    62             4             
3  Liverpool               20   10     57    44             0             
4  Arsenal                 19    8     63    59             3             
5  Tottenham Hotspur       17   12     57    48             3             
6  Bolton Wanderers        16   14     47    84             4             
7  Reading                 16   15     52    38             3             
8  Blackburn Rovers        15   16     52    77             6             
9  Everton                 15   10     52    65             2             
10 Portsmouth              14   12     45    48             1             
11 Middlesbrough           12   16     44    64             2             
12 West Ham United         12   21     35    85             2             
13 Aston Villa             11   10     43    48             1             
14 Manchester City         11   18     29    59             4             
15 Newcastle United        11   17     38    65             1             
16 Sheffield United        10   20     32    68             2             
17 Wigan Athletic          10   20     37    73             3             
18 Charlton Athletic        8   20     34    56             4             
19 Fulham                   8   15     38    56             3             
20 Watford                  5   20     29    45             2             
21 Manchester United       27    5     80    51             2             
22 Chelsea                 25    3     65    63             5             
23 Arsenal                 24    3     74    55             3             
24 Liverpool               21    4     67    45             1             
25 Everton                 19   11     55    40             3             
26 Aston Villa             16   10     71    54             4             
27 Portsmouth              16   13     48    55             3             
28 Blackburn Rovers        15   10     50    72             6             
29 Manchester City         15   13     45    50             4             
30 West Ham United         13   15     42    63             1             
⋮  ⋮                       ⋮    ⋮      ⋮     ⋮              ⋮             
51 Stoke City              12   17      38   73             5             
52 Wigan Athletic          12   17      34   59             4             
53 Bolton Wanderers        11   19      41   62             1             
54 Blackburn Rovers        10   17      40   74             4             
55 Portsmouth              10   17      38   58             5             
56 Sunderland               9   20      34   69             1             
57 Hull City                8   19      39   71             3             
58 West Bromwich Albion     8   22      36   67             1             
59 Middlesbrough            7   20      28   55             3             
60 Newcastle United         7   18      40   57             8             
61 Chelsea                 27    6     103   54             5             
62 Manchester United       27    7      86   49             4             
63 Arsenal                 23    9      83   56             1             
64 Tottenham Hotspur       21   10      67   58             1             
65 Liverpool               18   11      61   55             5             
66 Manchester City         18    7      73   49             2             
67 Aston Villa             17    8      52   59             2             
68 Everton                 16    9      60   57             2             
69 Birmingham City         13   14      38   74             1             
70 Blackburn Rovers        13   14      41   57             2             
71 Fulham                  12   16      39   46             1             
72 Stoke City              1

In [130]:
stats[stats$season <= '2009-2007',c('team','big_chance_missed','season')]

team                 big_chance_missed season   
1  Manchester United    NA                2006-2007
2  Chelsea              NA                2006-2007
3  Liverpool            NA                2006-2007
4  Arsenal              NA                2006-2007
5  Tottenham Hotspur    NA                2006-2007
6  Bolton Wanderers     NA                2006-2007
7  Reading              NA                2006-2007
8  Blackburn Rovers     NA                2006-2007
9  Everton              NA                2006-2007
10 Portsmouth           NA                2006-2007
11 Middlesbrough        NA                2006-2007
12 West Ham United      NA                2006-2007
13 Aston Villa          NA                2006-2007
14 Manchester City      NA                2006-2007
15 Newcastle United     NA                2006-2007
16 Sheffield United     NA                2006-2007
17 Wigan Athletic       NA                2006-2007
18 Charlton Athletic    NA                2006-2007
19 Fulham               NA                2006-2007
20 Watford              NA                2006-2007
21 Manchester United    NA                2007-2008
22 Chelsea              NA                2007-2008
23 Arsenal              NA                2007-2008
24 Liverpool            NA                2007-2008
25 Everton              NA                2007-2008
26 Aston Villa          NA                2007-2008
27 Portsmouth           NA                2007-2008
28 Blackburn Rovers     NA                2007-2008
29 Manchester City      NA                2007-2008
30 West Ham United      NA                2007-2008
31 Newcastle United     NA                2007-2008
32 Sunderland           NA                2007-2008
33 Tottenham Hotspur    NA                2007-2008
34 Middlesbrough        NA                2007-2008
35 Reading              NA                2007-2008
36 Wigan Athletic       NA                2007-2008
37 Bolton Wanderers     NA                2007-2008
38 Birmingham City      NA                2007-2008
39 Fulham               NA                2007-2008
40 Derby County         NA                2007-2008
41 Manchester United    NA                2008-2009
42 Chelsea              NA                2008-2009
43 Liverpool            NA                2008-2009
44 Arsenal              NA                2008-2009
45 Aston Villa          NA                2008-2009
46 Everton              NA                2008-2009
47 Manchester City      NA                2008-2009
48 Fulham               NA                2008-2009
49 Tottenham Hotspur    NA                2008-2009
50 West Ham United      NA                2008-2009
51 Stoke City           NA                2008-2009
52 Wigan Athletic       NA                2008-2009
53 Bolton Wanderers     NA                2008-2009
54 Blackburn Rovers     NA                2008-2009
55 Portsmouth           NA                2008-2009
56 Sunderland           NA                2008-2009
57 Hull City            NA                2008-2009
58 West Bromwich Albion NA                2008-2009
59 Middlesbrough        NA                2008-2009
60 Newcastle United     NA                2008-2009